// This file is released under the 3-clause BSD license. See COPYING-BSD.
// Generated by builder.sce : Please, do not edit this file
// cleaner.sce
// ------------------------------------------------------
curdir = pwd();
cleaner_path = get_file_path('cleaner.sce');
chdir(cleaner_path);
// ------------------------------------------------------
if fileinfo('loader.sce') <> [] then
  mdelete('loader.sce');
end
// ------------------------------------------------------
if fileinfo('libbuild_lib.so') <> [] then
  mdelete('libbuild_lib.so');
end
// ------------------------------------------------------
if fileinfo('libbuild_lib.cpp') <> [] then
  mdelete('libbuild_lib.cpp');
end
// ------------------------------------------------------
if fileinfo('libbuild_lib.hxx') <> [] then
  mdelete('libbuild_lib.hxx');
end
// ------------------------------------------------------
if fileinfo('libbuild_lib.h') <> [] then
  mdelete('libbuild_lib.h');
end
// ------------------------------------------------------
chdir(curdir);
// ------------------------------------------------------
